@server = 127.0.0.1:8000

### get all data/ without query
GET http://{{server}}/
###

### get data with query title
GET http://{{server}}/?title=Girls%20in%20The%20Dark
###

### get data with query author
GET http://{{server}}/?author=Akiyoshi%20Rikako
###

### get data with query title and author
GET http://{{server}}/?title=Girls%20in%20The%20Dark&author=Akiyoshi%20Rikako
###

### get data with non acceptable query
GET http://{{server}}/?coba=ngawur
###

### get data with query title and non acceptable query
GET http://{{server}}/?title=Girls%20in%20The%20Dark&coba=ngawur
###

### add new data
POST http://{{server}}/
Content-Type: application/json

{
    "title":"I Am A Cat", 
    "author":"Soseki Natsume", 
    "publisher":"Immortal Publishing", 
    "total_page":532, 
    "current_page":0, 
    "status":"TBR"
}
###

### change existing data
PUT http://{{server}}/
Content-Type: application/json

{
    "title":"Gagal Menjadi Manusia", 
    "author":"Dazai Osamu", 
    "publisher":"Penerbit Mai", 
    "total_page":156, 
    "current_page":90, 
    "status":"Reading"
}
###

### change non-existing data
PUT http://{{server}}/
Content-Type: application/json

{
    "title":"Kaki Kuda", 
    "author":"Akutagawa Ryuunosuke", 
    "publisher":"Penerbit Mai", 
    "total_page":0, 
    "current_page":0, 
    "status":"TBR"
}
###

### delete existing data by title & author name, but there is more than one data with the same title & author
DELETE http://{{server}}/
Content-Type: application/json

{
    "title":"Gagal Menjadi Manusia", 
    "author":"Dazai Osamu"
}
###

### delete non-existing data by title & author name
DELETE http://{{server}}/
Content-Type: application/json

{
    "title":"Kaki Kuda", 
    "author":"Akutagawa Ryuunosuke"
}
###

### delete based on ID
DELETE http://{{server}}/
Content-Type: application/json

{
    "id":9
}